const PATTERNS = {
	DOUBLE_HIT_UP: (time)=> {
    return [
      NOTES.MAKENOTES(time, NOTES.BLOCK_INDEX.FAR_RIGHT, NOTES.BLOCK_HEIGHT.MIDDLE, NOTES.BLOCK_COLOUR.BLUE, NOTES.CUT_DIRECTION.UP),
    NOTES.MAKENOTES(time, NOTES.BLOCK_INDEX.FAR_LEFT, NOTES.BLOCK_HEIGHT.MIDDLE, NOTES.BLOCK_COLOUR.RED, NOTES.CUT_DIRECTION.UP)]
	},
	DOUBLE_HIT_DOWN: (time)=> {
    return[
    NOTES.MAKENOTES(time, NOTES.BLOCK_INDEX.FAR_RIGHT, NOTES.BLOCK_HEIGHT.MIDDLE, NOTES.BLOCK_COLOUR.BLUE, NOTES.CUT_DIRECTION.DOWN),  
    NOTES.MAKENOTES(time, NOTES.BLOCK_INDEX.FAR_LEFT, NOTES.BLOCK_HEIGHT.MIDDLE, NOTES.BLOCK_COLOUR.RED, NOTES.CUT_DIRECTION.DOWN)]
	}
}

